/// One quote per day, selected randomly by date (same quote all day).
String getDailyQuote() => getQuoteForDate(DateTime.now());

/// Returns the deterministic daily quote for any given [date].
String getQuoteForDate(DateTime date) {
  final key = date.toIso8601String().substring(0, 10); // YYYY-MM-DD
  int hash = 0;
  for (int i = 0; i < key.length; i++) {
    hash = key.codeUnitAt(i) + ((hash << 5) - hash);
  }
  return _quotes[hash.abs() % _quotes.length];
}

const List<String> _quotes = [
  "Worth exists without needing proof.",
  "You are not too much. You are exactly enough.",
  "Survival carries silent pride.",
  "Healing unfolds in its own time.",
  "Enough has always been the truth.",
  "You are your own home.",
  "Strength grows in unseen places.",
  "Peace exists within reach.",
  "Authenticity carries its own beauty.",
  "You deserve gentle days.",
  "Confidence grows without permission.",
  "You are already worthy.",
  "Becoming never stops.",
  "Your voice deserves to be heard.",
  "Nothing is missing here.",
  "You are allowed to choose yourself.",
  "Storms reveal unshaken roots.",
  "Rest restores what effort cannot.",
  "Independence creates freedom.",
  "You rise every single time.",
  "Presence alone carries meaning.",
  "Your strength lives in your softness.",
  "Healing transforms everything.",
  "You are stronger than your hardest days.",
  "Freedom begins internally.",
  "You are becoming who you needed.",
  "Selfhood deserves loyalty.",
  "Every scar is proof of survival.",
  "Calm becomes home again.",
  "You belong to yourself.",
  "Evolution continues naturally.",
  "You are unfolding beautifully.",
  "Courage lives in continuing.",
  "Your independence is your freedom.",
  "Growth happens daily.",
  "You do not need fixing.",
  "Strength forms in silence.",
  "Peace belongs to you.",
  "Identity forms beyond expectations.",
  "You trust your intuition.",
  "Rest is never weakness.",
  "You are enough on your own.",
  "Transformation builds confidence.",
  "Your worth is not negotiable.",
  "Self-trust becomes foundation.",
  "You are stepping into your power.",
  "Nothing endured was meaningless.",
  "Healing never requires perfection.",
  "Confidence stabilizes everything.",
  "You are becoming fearless.",
  "Individuality holds quiet power.",
  "Your courage grows with every step.",
  "Expansion defines life.",
  "You are growing through everything.",
  "Silence restores balance.",
  "You are safe within yourself.",
  "Power often appears quietly.",
  "You create your own path.",
  "Progress forms quietly.",
  "You are evolving beyond doubt.",
  "Letting go creates space for calm.",
  "You were born complete.",
  "Survival transforms into wisdom.",
  "Peace returns naturally.",
  "Authority exists within self.",
  "You are becoming limitless.",
  "No comparison defines truth.",
  "Your resilience is your signature.",
  "Calm grows naturally.",
  "You stand in your truth.",
  "Becoming reveals truth.",
  "You are walking into your future.",
  "Endurance shapes quiet power.",
  "Your survival is your rebellion.",
  "Change creates strength.",
  "You are writing your own story.",
  "Rest rebuilds identity.",
  "You are returning to yourself.",
  "Self-belief becomes permanent.",
  "You rise by believing in yourself.",
  "Enoughness requires no validation.",
  "You were never meant to shrink.",
  "Strength lives beneath calm.",
  "Healing becomes visible slowly.",
  "Direction forms from within.",
  "You are discovering new strength.",
  "Being is enough.",
  "You carry strength you haven't met yet.",
  "Expansion creates freedom.",
  "You are blooming in your own season.",
  "Gentle days rebuild strength.",
  "You deserve calm.",
  "Confidence transforms everything.",
  "You are unstoppable once you decide.",
  "Existence itself holds value.",
  "Your presence matters.",
  "Survival carries dignity.",
  "Peace is your birthright.",
  "Self-trust creates calm.",
  "You define your own life.",
  "Growth restores self.",
  "You are not behind. You are becoming.",
  "Rising happens again and again.",
  "Healing continues forward.",
  "Freedom expands naturally.",
  "You are expanding beyond fear.",
  "Completeness exists in this moment.",
  "You are allowed to grow differently.",
  "Endurance leaves permanent strength.",
  "Your healing is sacred.",
  "Trust replaces doubt.",
  "You are your own protector.",
  "Transformation continues endlessly.",
  "You are becoming unstoppable.",
  "Presence alone carries meaning.",
  "You do not chase. You attract.",
  "Every fall teaches rising.",
  "Your heart knows the way forward.",
  "Independence builds peace.",
  "You walk with purpose.",
  "Progress happens silently.",
  "You do not need permission to take up space.",
  "Strength becomes identity.",
  "Healing takes courage, and you are courageous.",
  "Power grows naturally.",
  "You are becoming your highest self.",
  "Existence is not a mistake.",
  "You are not hard to love.",
  "Softness survives everything.",
  "You are healing, even now.",
  "Confidence creates calm.",
  "You trust your own voice.",
  "Evolution strengthens identity.",
  "You are rising into your truth.",
  "Worth exists without effort.",
  "You deserve the same love you give others.",
  "Standing again becomes natural.",
  "You are not your past.",
  "Courage becomes identity.",
  "You choose what chooses you.",
  "Becoming creates freedom.",
  "You are allowed to start again.",
  "Strength rebuilds quietly.",
  "Your soul knows how to recover.",
  "Inner voice leads correctly.",
  "You are not late. You are right on time.",
  "Nothing about this existence is accidental.",
  "You are not defined by anyone's expectations.",
  "Survival creates wisdom.",
  "You rebuild yourself with grace.",
  "Change brings clarity.",
  "You are allowed to pause.",
  "Clarity builds strength.",
  "You are not fragile. You are forged.",
  "Becoming feels natural.",
  "You continue, and that is enough.",
  "Strength grows silently.",
  "You bend, but you do not break.",
  "Calm strengthens identity.",
  "You are safe within yourself.",
  "Expansion reveals strength.",
  "You are evolving.",
  "Growth creates peace.",
  "Your existence is your first victory.",
  "Resilience defines identity.",
  "You carry power in your calm.",
  "Transformation reveals truth.",
  "You are becoming everything you were meant to be.",
  "Healing restores clarity.",
  "You are allowed to let go.",
  "Freedom belongs internally.",
  "You belong fully to yourself.",
  "Strength rises quietly.",
  "You are unbreakable in ways unseen.",
  "Peace restores balance.",
  "You are enough. Always.",
  "Confidence lives within calm.",
  "You create your own life.",
  "Becoming restores identity.",
  "You are powerful beyond measure.",
  "Growth expands everything.",
  "You are stepping forward.",
  "Survival creates strength.",
  "You are becoming stronger daily.",
  "Healing belongs here.",
  "You are returning home to yourself.",
  "Independence protects peace.",
  "You trust your inner truth.",
  "Transformation builds resilience.",
  "You rise again. Always.",
  "Progress defines becoming.",
  "You are whole already.",
  "Strength exists within.",
  "You are becoming calm.",
  "Peace exists within reach.",
  "You are enough in every moment.",
  "Becoming never ends.",
  "You are becoming free.",
  "Growth defines becoming.",
  "You are enough.",
];
